# Generated by Django 5.2.2 on 2025-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('audio', 'Audio Devices'), ('camera', 'Cameras'), ('accessory', 'Accessories'), ('other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
